services:
  db:
    image: neo4j:4.4.15-community
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/test
      # On fixe les limites pour tenir dans les 3G de RAM
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=1G
    deploy:
      resources:
        limits:
          memory: 3g

  app:
    image: neo4jtp:latest
    depends_on:
      - db
    environment:
      - JSON_FILE=http://vmrum.isc.heia-fr.ch/files/DBLP-Citation-network-V18.jsonl
      - MAX_NODES=10000000
      - BATCH_SIZE=15000
      - NEO4J_IP=db
      - JAVA_TOOL_OPTIONS=-Xmx2500m -Xms512m -XX:+UseG1GC
    deploy:
      resources:
        limits:
          memory: 3g

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf: