apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: advdb
data:
  JSON_FILE: "http://vmrum.isc.heia-fr.ch/files/DBLP-Citation-network-V18.jsonl"
  MAX_NODES: "10000"
  NEO4J_IP: "neo4j"
  NEO4J_PORT: "7687"
