apiVersion: batch/v1
kind: Job
metadata:
  name: app-ray-ste-adv-daba-26
  namespace: ray-ste-adv-daba-26
  labels:
    app: advdb-app
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: advdb-app
    spec:
      restartPolicy: Never
      containers:
      - name: app
        image: ghcr.io/evarayheig/advdaba-tp2:3b7920a518cf3eced3359c0b49d06e3fdc41adb2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "2000m"
      initContainers:
      - name: wait-for-neo4j
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z neo4j 7687; do echo waiting for neo4j...; sleep 2; done;']
